# Generated by Django 3.1.5 on 2021-01-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('wind', models.CharField(max_length=255)),
                ('cloudiness', models.CharField(max_length=255)),
                ('pressure', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('sunrise', models.CharField(max_length=255)),
                ('sunset', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
